# dev file

services:
  hn-parser-node:
    container_name: hn-parser-node
    image: nemanjamitic/hn-parser-node:latest
    build:
      context: .
      dockerfile: Dockerfile
      # args:
      #   - BUILDKIT_PROGRESS=plain
    restart: unless-stopped
    environment:
      - PORT=3007
    env_file:
      - .env.local
    volumes:
      - ./data:/app/data
      - ./data/cron/cron.log:/var/log/cron.log # fix root
    networks:
      - default

networks:
  default:
    name: hn-parser-node-default
    external: false
