# dev file

services:
  hn-parser-node:
    container_name: hn-parser-node
    restart: unless-stopped
    image: nemanjamitic/hn-parser-node:latest
    build:
      context: .
      dockerfile: Dockerfile
      # args:
      #   - BUILDKIT_PROGRESS=plain
    env_file:
      - .env.local
    ports:
      - '3007:3007'
    environment:
      - PORT=3007
    # fixes file permissions for volume
    # uid=1000(username) gid=1000(username)
    user: '${MY_UID}:${MY_GID}'
    volumes:
      - ./data:/app/data
    networks:
      - default

networks:
  default:
    name: hn-parser-node-default
    external: false
