version: '3.8'

# prod file

services:
  hn-parser-node:
    image: nemanjamitic/hn-parser-node:latest
    container_name: hn-parser-node
    restart: unless-stopped
    environment:
      - PORT=3007
    env_file:
      - .env.local # use single .env
    volumes:
      - ./data:/app/data
      - ./data/cron/cron.log:/var/log/cron.log # fix root
    networks:
      - proxy
    labels:
      - 'traefik.enable=true'
      - 'traefik.docker.network=proxy'
      - 'traefik.http.routers.hn-parser-node-secure.rule=Host(`${SITE_HOSTNAME}`)'
      - 'traefik.http.routers.hn-parser-node-secure.entrypoints=websecure'
      - 'traefik.http.routers.hn-parser-node-secure.service=hn-parser-node-svc'
      - 'traefik.http.services.hn-parser-node-svc.loadbalancer.server.port=3007'

networks:
  proxy:
    external: true
